name: Artwork Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Run script
          run: |
            chmod +x dragon.sh
            ./dragon.sh