name: Artwork Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Run script
          run: |
            chmod +x dragon.sh
            ./dragon.sh
        - name: Upload Dragon file
          uses: actions/upload-artifact@v4
          with:
            name: Upload-dragon
            path: dragon.txt
        
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: Download a dragon
          uses: actions/download-artifact@v4
          with:
            name: Upload-dragon
        - name: sample step from second job
          run: grep -i "dragon" dragon.txt
    third_job:
        needs: second_job
        runs-on: ubuntu-latest
        steps:
        - name: Download a dragon
          uses: actions/download-artifact@v4
          with:
            name: Upload-dragon
        - name: sample step from third job
          run: cat dragon.txt