name: Artwork Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Run script
          run: |
            chmod +x dragon.sh
            ./dragon.sh
    second_job:
        runs-on: ubuntu-latest
        steps:
        - name: sample step from second job
          run: grep -i "dragon" dragon.txt
    third_job:
        runs-on: ubuntu-latest
        steps:
        - name: sample step from third job
          run: cat dragon.txt