name: Sample Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome to my workflow
          run: echo "Welcome"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md