name: Sample Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List files
          run: |
            ls
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon " Run for me...I am dragon who breaths fire.." >> dragon.txt